name = "CatabraFFT"
uuid = "e98b41f6-08eb-47d9-bc43-d6946b72e3e5"
authors = ["Evangelos Kyriakos <ekyriakos@ece.auth.gr> and Nikos Pitsianis <pitsiani@ece.auth.gr>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
